CREATE TABLE IF NOT EXISTS `db_imitationdaily`.`yaganyong_img` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `likes` BIGINT(20) UNSIGNED NULL DEFAULT 0 COMMENT '点赞数',
  `url` VARCHAR(255) NULL COMMENT '图片的链接',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;